
FROM mirkokiefer/base

RUN apt-get update

RUN apt-get install -y wget openjdk-6-jre

RUN curl https://download.elasticsearch.org/logstash/logstash/logstash-1.3.3-flatjar.jar > /logstash-1.3.3-flatjar.jar
